project_id = "jrzeabjpxkhccopxfwqa"

[functions.export-pdf-report]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = false

[functions.scrape-website-content]
verify_jwt = false

[functions.save-simulation-scenario]
verify_jwt = false

[functions.validate-simulation-code]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.create-pms-user]
verify_jwt = true

[functions.regenerate-schedule-items]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-approval-email]
verify_jwt = true

[functions.send-application-email]
verify_jwt = true

[functions.fix-partial-payments]
verify_jwt = true
